#!/bin/bash
#change dir to project directory
PYTHON_DIR=~/networks_project/Networks_Game_Project
IFACE="lo"
scenarios=("none" "loss_2" "loss_5" "delay_100")

get_netem_command() {
    case "$1" in
        "none") echo "" ;;
        "loss_2") echo "loss 2%" ;;
        "loss_5") echo "loss 5%" ;;
        "delay_100") echo "delay 100ms" ;;
        *) echo "" ;;
    esac
}

safe_tc_qdisc_del() {
    local iface=$1
    if sudo tc qdisc show dev "$iface" | grep -q "netem"; then
        sudo tc qdisc del dev "$iface" root
    fi
}

echo "-------------------------------"
echo " Running scenario: Baseline"
echo "-------------------------------"

safe_tc_qdisc_del "$IFACE"

cd "$PYTHON_DIR" || exit 1

# Start tcpdump
sudo tcpdump -i lo -w "pcap_baseline.pcap" &
TCPDUMP_PID=$!
sleep 2  # ensure tcpdump is ready

# Start server
python3 server/server.py &
SERVER_PID=$!
sleep 2

# Start client in automation mode
AUTO_USERNAME="testuser" AUTOMATE=1 python3 client/start_game.py &
CLIENT_PID=$!

# Wait for client automation duration (match automated_play duration in Python!)
sleep 20

kill $CLIENT_PID 2>/dev/null
kill $SERVER_PID 2>/dev/null
kill $TCPDUMP_PID 2>/dev/null
sleep 1
# Remove netem rule
safe_tc_qdisc_del "$IFACE"

# Move metrics CSV generated by client
if [ -f metrics.csv ]; then
    mv metrics.csv "metrics_${scenario}.csv"
else
    echo "Warning: metrics.csv not found for scenario $scenario"
fi

echo " Completed: $scenario"
echo ""

deactivate
echo "All scenarios complete."

